export const rematesData = [
    {
        dia: '31',
        mes: '03',
        horaInicio: '09:00',
        horaCierre: '24:00',
        titulo: '254˚ Pantalla Uruguay',
        lugar: 'Parque Tecnológico del LATU',
        organiza: 'Pantalla Uruguay',
        enlace: '7mxGicUCujo',
        miniatura: 'pantallauruguay.jpg',
    },
    {
        dia: '31',
        mes: '03',
        horaInicio: '14:00',
        horaCierre: '24:00',
        titulo: 'DSR Cardal',
        lugar: 'Local Cardal, Florida',
        organiza: 'Escritorio DiSanti',
        enlace: 'xJW7jTWYJd0',
        miniatura: 'dsr.jpeg',
    },
    {
        dia: '31',
        mes: '03',
        horaInicio: '12:00',
        horaCierre: '24:00',
        titulo: 'Liquidación total Establecimiento El Gato',
        lugar: 'Establecimiento El Gato',
        organiza: 'Soria Negocios Rurales',
        enlace: 'm9SWpFqg5Ew',
        miniatura: 'gato.jpg',
    },
    {
        dia: '31',
        mes: '03',
        horaInicio: '09:00',
        horaCierre: '24:00',
        titulo: '186° REMATE LOTE 21',
        lugar: 'Club de Golf',
        organiza: 'Lote 21',
        enlace: '1btzIH_7Y7M',
        miniatura: 'lote21.jpg',
    },
]
